version: 2
jobs:
  build:
    working_directory: /cam-thesis
    docker:
      - image: urbas/cam-thesis:1.0.3
    steps:
      - checkout
      - run: ./.circleci/build.py
      - store_artifacts:
        path: build/pdfs
